### PR TITLE
Bug/4724 280 fix verify code screen field error

### LINKED ISSUE #280: Verification code field should get reset after navigating back and coming on screen again
#### Describe the bug / expected behavior
Actual result :- Verification code is there 

Expected result :- Verification code should be reset 

#### What are the steps to reproduce?

1. Open the BLI Fiji APP
2. Click on sign up 
3. Accept EULA 
4. Enter email . Click on next
5. Enter verification code

Issue 1 :- 

1. Click on BACK 
2. Again click on next 

Actual result :- Verification code is there 

Expected result :- Verification code should be reset since a new verification code is sent on clicking on Next 

 Issue 2 :- 

1. Enter verification code
2. Click on next
3. Account detail page comes , click on back 
4. User is back to verification code page . 
5. Actual result :- Verification code is there 

Expected result :- Verification code should be reset since a older one is expired now 

#### Screenshots / Screen recording

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/d97c3c8e-a6c6-4a75-9eeb-46fcf3a64356

https://github.com/etn-ccis/blui-react-native-workflows/assets/122432797/5e2e6894-98f6-41a9-88e5-89dd60e50203

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes #280 BLUI-4724

#### Changes proposed in this Pull Request:

- Fixed verify code screen input field issue
- Reset input field on next, back and resend button

#### Screenshots / Screen Recording (if applicable)

- 

https://github.com/etn-ccis/blui-react-native-workflows/assets/120575281/a3101172-4907-41d5-9678-85a5ba26dcfd

#### To Test:

- cd login-workflow
- yarn start:example
- Click on Register Now button
- Go through the flow till Verify Email screen
- Enter any valid value in the input field
- Click on Resend, Back or Next to see the field value is reset

#### Any specific feedback you are looking for?

-

### CODE REVIEW

File: login-workflow/src/screens/SelfRegistrationPager.tsx [hunk 1]
```diff
@@ -150,6 +150,7 @@ export const SelfRegistrationPager: React.FC<SelfRegistrationPagerProps> = (prop
     const [accountAlreadyExists, setAccountAlreadyExists] = useState<boolean>(false);
     const [hasAcknowledgedError, setHasAcknowledgedError] = useState(false);
     const [currentPage, setCurrentPage] = useState(0);
+    const [resetInputField, setResetInputField] = useState(false);
```
Comment (joebochill) [inline login-workflow/src/screens/SelfRegistrationPager.tsx:153]: This is kind of clunky — would it not be simpler to have a useEffect that clears the code whenever you come to the VerifyCode screen? Then you don't have a variable that tracks the code and a separate variable that tracks whether we should ignore the variable that tracks the code.

**Review by ektaghag-eaton — APPROVED** [review]
UseEffect changes working fine.
